### ISSUE TITLE
Change of credits

### ISSUE THREAD

**Issue by anbuchelva** [andreasrsa/openwrt-archerc5#1]
Thanks for putting all the steps together. One thing to note, the patch was done by Serge Vasilugin (you may find it from the patch itself), not me. I'm an user just like you, tried to compile the binaries from the source. For some reason I couldn't make it work as my ISP has some control over the router.

I request you change the credits to https://github.com/ggbruno

**Comment by andreasrsa** [comment]
Ok, will do. Thanks for that.
